name: CI CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint -- --max-warnings=0

      - name: Run Prettier check
        run: npm run format:check

  deploy:
    runs-on: ubuntu-latest
    needs: lint-and-format
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/tpms-frontend/
            git reset --hard HEAD
            git pull origin main
            npm i
            npm run build
